const parameters = {
              "steps": [
                  {
                  "title": "Plans Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "plans",
                          "type": "section",
                          "title": "Plans CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Plans",
                          "childFields": [
                                {
                                  "name": "plans_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "name",
                                  "label": "Name",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_name",
                                  "alias" : "plans.name",
                                  },
                                  {
                                  "name": "duration_type",
                                  "label": "Duration Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_durationType",
                                  "alias" : "plans.duration_type",
                                  },
                                  {
                                  "name": "ai_credits_amount",
                                  "label": "Ai Credits Amount",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_aiCreditsAmount",
                                  "alias" : "plans.ai_credits_amount",
                                  },
                                  {
                                  "name": "currency_id",
                                  "label": "Currency Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_currencyId",
                                  "alias" : "plans.currency_id",
                                  },
                                  {
                                  "name": "services",
                                  "label": "Services",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_services",
                                  "alias" : "plans.services",
                                  },
                                  {
                                  "name": "price",
                                  "label": "Price",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_price",
                                  "alias" : "plans.price",
                                  },
                                  {
                                  "name": "region",
                                  "label": "Region",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_region",
                                  "alias" : "plans.region",
                                  },
                                  {
                                  "name": "is_active",
                                  "label": "Is Active",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_isActive",
                                  "alias" : "plans.is_active",
                                  },
                                  {
                                  "name": "is_public",
                                  "label": "Is Public",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "plans_isPublic",
                                  "alias" : "plans.is_public",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'plans_id' : 'id',  'plans_name' : 'name',  'plans_durationType' : 'duration_type',  'plans_aiCreditsAmount' : 'ai_credits_amount',  'plans_currencyId' : 'currency_id',  'plans_services' : 'services',  'plans_price' : 'price',  'plans_region' : 'region',  'plans_isActive' : 'is_active',  'plans_isPublic' : 'is_public',  'plans_createdBy' : 'created_by',  'plans_updatedBy' : 'updated_by',  'plans_status' : 'status',  'plans_createdAt' : 'created_at',  'plans_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;