const parameters = {
              "steps": [
                  {
                  "title": "Application Subscriptions Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "application_subscriptions",
                          "type": "section",
                          "title": "Application Subscriptions CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Application_subscriptions",
                          "childFields": [
                                {
                                  "name": "applicationSubscriptions_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "urdd_id",
                                  "label": "Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_urddId",
                                  "alias" : "application_subscriptions.urdd_id",
                                  },
                                  {
                                  "name": "plan_id",
                                  "label": "Plan Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_planId",
                                  "alias" : "application_subscriptions.plan_id",
                                  },
                                  {
                                  "name": "user_payment_method_id",
                                  "label": "User Payment Method Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_userPaymentMethodId",
                                  "alias" : "application_subscriptions.user_payment_method_id",
                                  },
                                  {
                                  "name": "discount_id",
                                  "label": "Discount Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_discountId",
                                  "alias" : "application_subscriptions.discount_id",
                                  },
                                  {
                                  "name": "start_date",
                                  "label": "Start Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_startDate",
                                  "alias" : "application_subscriptions.start_date",
                                  },
                                  {
                                  "name": "expiry_date",
                                  "label": "Expiry Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_expiryDate",
                                  "alias" : "application_subscriptions.expiry_date",
                                  },
                                  {
                                  "name": "is_trial",
                                  "label": "Is Trial",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_isTrial",
                                  "alias" : "application_subscriptions.is_trial",
                                  },
                                  {
                                  "name": "trial_end_date",
                                  "label": "Trial End Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_trialEndDate",
                                  "alias" : "application_subscriptions.trial_end_date",
                                  },
                                  {
                                  "name": "auto_renew",
                                  "label": "Auto Renew",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "applicationSubscriptions_autoRenew",
                                  "alias" : "application_subscriptions.auto_renew",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'application_subscriptions_id' : 'id',  'application_subscriptions_urddId' : 'urdd_id',  'application_subscriptions_planId' : 'plan_id',  'application_subscriptions_userPaymentMethodId' : 'user_payment_method_id',  'application_subscriptions_discountId' : 'discount_id',  'application_subscriptions_startDate' : 'start_date',  'application_subscriptions_expiryDate' : 'expiry_date',  'application_subscriptions_isTrial' : 'is_trial',  'application_subscriptions_trialEndDate' : 'trial_end_date',  'application_subscriptions_autoRenew' : 'auto_renew',  'application_subscriptions_createdBy' : 'created_by',  'application_subscriptions_updatedBy' : 'updated_by',  'application_subscriptions_status' : 'status',  'application_subscriptions_createdAt' : 'created_at',  'application_subscriptions_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;