const parameters = {
              "steps": [
                  {
                  "title": "Referrals Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "referrals",
                          "type": "section",
                          "title": "Referrals CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Referrals",
                          "childFields": [
                                {
                                  "name": "referrals_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "referrer_urdd_id",
                                  "label": "Referrer Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_referrerUrddId",
                                  "alias" : "referrals.referrer_urdd_id",
                                  },
                                  {
                                  "name": "referred_urdd_id",
                                  "label": "Referred Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_referredUrddId",
                                  "alias" : "referrals.referred_urdd_id",
                                  },
                                  {
                                  "name": "referral_code",
                                  "label": "Referral Code",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_referralCode",
                                  "alias" : "referrals.referral_code",
                                  },
                                  {
                                  "name": "reward_credits",
                                  "label": "Reward Credits",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_rewardCredits",
                                  "alias" : "referrals.reward_credits",
                                  },
                                  {
                                  "name": "completed_at",
                                  "label": "Completed At",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "referrals_completedAt",
                                  "alias" : "referrals.completed_at",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'referrals_id' : 'id',  'referrals_referrerUrddId' : 'referrer_urdd_id',  'referrals_referredUrddId' : 'referred_urdd_id',  'referrals_referralCode' : 'referral_code',  'referrals_rewardCredits' : 'reward_credits',  'referrals_completedAt' : 'completed_at',  'referrals_createdBy' : 'created_by',  'referrals_updatedBy' : 'updated_by',  'referrals_status' : 'status',  'referrals_createdAt' : 'created_at',  'referrals_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;