const parameters = {
              "steps": [
                  {
                  "title": "Semesters Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "semesters",
                          "type": "section",
                          "title": "Semesters CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Semesters",
                          "childFields": [
                                {
                                  "name": "semesters_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "program_id",
                                  "label": "Program Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_programId",
                                  "alias" : "semesters.program_id",
                                  },
                                  {
                                  "name": "semester_num",
                                  "label": "Semester Num",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_semesterNum",
                                  "alias" : "semesters.semester_num",
                                  },
                                  {
                                  "name": "start_date",
                                  "label": "Start Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_startDate",
                                  "alias" : "semesters.start_date",
                                  },
                                  {
                                  "name": "end_date",
                                  "label": "End Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_endDate",
                                  "alias" : "semesters.end_date",
                                  },
                                  {
                                  "name": "semester_name",
                                  "label": "Semester Name",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "semesters_semesterName",
                                  "alias" : "semesters.semester_name",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'semesters_semesterId' : 'semester_id',  'semesters_programId' : 'program_id',  'semesters_semesterNum' : 'semester_num',  'semesters_startDate' : 'start_date',  'semesters_endDate' : 'end_date',  'semesters_semesterName' : 'semester_name',  'semesters_status' : 'status',  'semesters_createdBy' : 'created_by',  'semesters_updatedBy' : 'updated_by',  'semesters_createdAt' : 'created_at',  'semesters_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;