const parameters = {
              "steps": [
                  {
                  "title": "Registereddevices Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "registereddevices",
                          "type": "section",
                          "title": "Registereddevices CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Registereddevices",
                          "childFields": [
                                {
                                  "name": "registereddevices_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "device_name",
                                  "label": "Device Name",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_deviceName",
                                  "alias" : "registereddevices.device_name",
                                  },
                                  {
                                  "name": "device_token",
                                  "label": "Device Token",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_deviceToken",
                                  "alias" : "registereddevices.device_token",
                                  },
                                  {
                                  "name": "device_type",
                                  "label": "Device Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_deviceType",
                                  "alias" : "registereddevices.device_type",
                                  },
                                  {
                                  "name": "access_token",
                                  "label": "Access Token",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_accessToken",
                                  "alias" : "registereddevices.access_token",
                                  },
                                  {
                                  "name": "token_expiry",
                                  "label": "Token Expiry",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_tokenExpiry",
                                  "alias" : "registereddevices.token_expiry",
                                  },
                                  {
                                  "name": "device_os",
                                  "label": "Device Os",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_deviceOs",
                                  "alias" : "registereddevices.device_os",
                                  },
                                  {
                                  "name": "make",
                                  "label": "Make",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "registereddevices_make",
                                  "alias" : "registereddevices.make",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'registereddevices_deviceId' : 'device_id',  'registereddevices_deviceName' : 'device_name',  'registereddevices_deviceToken' : 'device_token',  'registereddevices_deviceType' : 'device_type',  'registereddevices_accessToken' : 'access_token',  'registereddevices_tokenExpiry' : 'token_expiry',  'registereddevices_deviceOs' : 'device_os',  'registereddevices_make' : 'make',  'registereddevices_status' : 'status',  'registereddevices_createdBy' : 'created_by',  'registereddevices_updatedBy' : 'updated_by',  'registereddevices_createdAt' : 'created_at',  'registereddevices_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;