const parameters = {
              "steps": [
                  {
                  "title": "Topicquestions Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "topicquestions",
                          "type": "section",
                          "title": "Topicquestions CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Topicquestions",
                          "childFields": [
                                {
                                  "name": "topicquestions_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "lecture_topic_id",
                                  "label": "Lecture Topic Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_lectureTopicId",
                                  "alias" : "topicquestions.lecture_topic_id",
                                  },
                                  {
                                  "name": "question_type",
                                  "label": "Question Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_questionType",
                                  "alias" : "topicquestions.question_type",
                                  },
                                  {
                                  "name": "question",
                                  "label": "Question",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_question",
                                  "alias" : "topicquestions.question",
                                  },
                                  {
                                  "name": "is_done",
                                  "label": "Is Done",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_isDone",
                                  "alias" : "topicquestions.is_done",
                                  },
                                  {
                                  "name": "created_at_date",
                                  "label": "Created At Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_createdAtDate",
                                  "alias" : "topicquestions.created_at_date",
                                  },
                                  {
                                  "name": "created_at_time",
                                  "label": "Created At Time",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_createdAtTime",
                                  "alias" : "topicquestions.created_at_time",
                                  },
                                  {
                                  "name": "updated_at_date",
                                  "label": "Updated At Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_updatedAtDate",
                                  "alias" : "topicquestions.updated_at_date",
                                  },
                                  {
                                  "name": "updated_at_time",
                                  "label": "Updated At Time",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "topicquestions_updatedAtTime",
                                  "alias" : "topicquestions.updated_at_time",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'topicquestions_topicQuestionId' : 'topic_question_id',  'topicquestions_lectureTopicId' : 'lecture_topic_id',  'topicquestions_questionType' : 'question_type',  'topicquestions_question' : 'question',  'topicquestions_isDone' : 'is_done',  'topicquestions_createdAtDate' : 'created_at_date',  'topicquestions_createdAtTime' : 'created_at_time',  'topicquestions_updatedAtDate' : 'updated_at_date',  'topicquestions_updatedAtTime' : 'updated_at_time',  'topicquestions_status' : 'status',  'topicquestions_createdBy' : 'created_by',  'topicquestions_updatedBy' : 'updated_by',  'topicquestions_createdAt' : 'created_at',  'topicquestions_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;