///New
export const REDUX_UPDATE_CURRENT_USER_ROLE = "REDUX_UPDATE_CURRENT_USER_ROLE";
export const REDUX_LOGOUT_CURRENT_USER = "REDUX_LOGOUT_CURRENT_USER";
export const REDUX_UPDATE_CURRENT_USER = "REDUX_UPDATE_CURRENT_USER";
export const REDUX_UPDATE_LOADING_STATE = "REDUX_UPDATE_LOADING_STATE";
export const REDUX_UPDATE_USER_DATA = "REDUX_UPDATE_USER_DATA";
export const REDUX_API_DOCUMENTATION = "REDUX_API_DOCUMENTATION";

export const GET_USERS_CHAT = "GET_USERS_CHAT";
export const REDUX_USERS_MESSAGE_BY_CHAT_ID = "REDUX_USERS_MESSAGE_BY_CHAT_ID";
export const REDUX_USERS_MESSAGE_BY_CHAT_ID_PAGINATED =
  "REDUX_USERS_MESSAGE_BY_CHAT_ID_PAGINATED";
export const REDUX_UPDATE_USERS_MESSAGE_BY_CHAT_ID =
  "REDUX_UPDATE_USERS_MESSAGE_BY_CHAT_ID";
export const REDUX_ADD_USERS_MESSAGE_BY_CHAT_ID =
  "REDUX_ADD_USERS_MESSAGE_BY_CHAT_ID";
export const REDUX_UPDATE_MESSAGE_STATUS_BY_CHAT_ID =
  "REDUX_UPDATE_MESSAGE_STATUS_BY_CHAT_ID";
//
export const REDUX_GET_USERS_CONTACTS = "REDUX_USERS_CONTACTS";
export const REDUX_UPDATE_USERS_CONTACTS = "REDUX_UPDATE_USERS_CONTACTS";
export const REDUX_ADD_USERS_CONTACTS = "REDUX_ADD_USERS_MESSAGE_BY_CHAT_ID";
export const REDUX_DELETE_USERS_CONTACTS = "REDUX_DELETE_USERS_CONTACTS";
export const REDUX_SET_PAGINATION_LOADING = "REDUX_SET_PAGINATION_LOADING";