const parameters = {
              "steps": [
                  {
                  "title": "User Payment Methods Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "user_payment_methods",
                          "type": "section",
                          "title": "User Payment Methods CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "User_payment_methods",
                          "childFields": [
                                {
                                  "name": "userPaymentMethods_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "urdd_id",
                                  "label": "Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_urddId",
                                  "alias" : "user_payment_methods.urdd_id",
                                  },
                                  {
                                  "name": "supported_payment_method_id",
                                  "label": "Supported Payment Method Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_supportedPaymentMethodId",
                                  "alias" : "user_payment_methods.supported_payment_method_id",
                                  },
                                  {
                                  "name": "payment_details",
                                  "label": "Payment Details",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_paymentDetails",
                                  "alias" : "user_payment_methods.payment_details",
                                  },
                                  {
                                  "name": "is_verified",
                                  "label": "Is Verified",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_isVerified",
                                  "alias" : "user_payment_methods.is_verified",
                                  },
                                  {
                                  "name": "verification_amount",
                                  "label": "Verification Amount",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_verificationAmount",
                                  "alias" : "user_payment_methods.verification_amount",
                                  },
                                  {
                                  "name": "verification_status",
                                  "label": "Verification Status",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_verificationStatus",
                                  "alias" : "user_payment_methods.verification_status",
                                  },
                                  {
                                  "name": "verification_transaction_id",
                                  "label": "Verification Transaction Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_verificationTransactionId",
                                  "alias" : "user_payment_methods.verification_transaction_id",
                                  },
                                  {
                                  "name": "is_default",
                                  "label": "Is Default",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_isDefault",
                                  "alias" : "user_payment_methods.is_default",
                                  },
                                  {
                                  "name": "is_active",
                                  "label": "Is Active",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userPaymentMethods_isActive",
                                  "alias" : "user_payment_methods.is_active",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'user_payment_methods_id' : 'id',  'user_payment_methods_urddId' : 'urdd_id',  'user_payment_methods_supportedPaymentMethodId' : 'supported_payment_method_id',  'user_payment_methods_paymentDetails' : 'payment_details',  'user_payment_methods_isVerified' : 'is_verified',  'user_payment_methods_verificationAmount' : 'verification_amount',  'user_payment_methods_verificationStatus' : 'verification_status',  'user_payment_methods_verificationTransactionId' : 'verification_transaction_id',  'user_payment_methods_isDefault' : 'is_default',  'user_payment_methods_isActive' : 'is_active',  'user_payment_methods_createdBy' : 'created_by',  'user_payment_methods_updatedBy' : 'updated_by',  'user_payment_methods_status' : 'status',  'user_payment_methods_createdAt' : 'created_at',  'user_payment_methods_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;