const parameters = {
              "steps": [
                  {
                  "title": "Subscription Renewal Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "subscription_renewal",
                          "type": "section",
                          "title": "Subscription Renewal CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Subscription_renewal",
                          "childFields": [
                                {
                                  "name": "subscriptionRenewal_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "subscription_id",
                                  "label": "Subscription Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_subscriptionId",
                                  "alias" : "subscription_renewal.subscription_id",
                                  },
                                  {
                                  "name": "transaction_id",
                                  "label": "Transaction Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_transactionId",
                                  "alias" : "subscription_renewal.transaction_id",
                                  },
                                  {
                                  "name": "credits_given",
                                  "label": "Credits Given",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_creditsGiven",
                                  "alias" : "subscription_renewal.credits_given",
                                  },
                                  {
                                  "name": "credits_used",
                                  "label": "Credits Used",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_creditsUsed",
                                  "alias" : "subscription_renewal.credits_used",
                                  },
                                  {
                                  "name": "renewal_type",
                                  "label": "Renewal Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_renewalType",
                                  "alias" : "subscription_renewal.renewal_type",
                                  },
                                  {
                                  "name": "logged_at",
                                  "label": "Logged At",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "subscriptionRenewal_loggedAt",
                                  "alias" : "subscription_renewal.logged_at",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'subscription_renewal_id' : 'id',  'subscription_renewal_subscriptionId' : 'subscription_id',  'subscription_renewal_transactionId' : 'transaction_id',  'subscription_renewal_creditsGiven' : 'credits_given',  'subscription_renewal_creditsUsed' : 'credits_used',  'subscription_renewal_renewalType' : 'renewal_type',  'subscription_renewal_loggedAt' : 'logged_at',  'subscription_renewal_createdBy' : 'created_by',  'subscription_renewal_updatedBy' : 'updated_by',  'subscription_renewal_status' : 'status',  'subscription_renewal_createdAt' : 'created_at',  'subscription_renewal_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;