const parameters = {
              "steps": [
                  {
                  "title": "Studentsemesters Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "studentsemesters",
                          "type": "section",
                          "title": "Studentsemesters CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Studentsemesters",
                          "childFields": [
                                {
                                  "name": "studentsemesters_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "student_user_id",
                                  "label": "Student User Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_studentUserId",
                                  "alias" : "studentsemesters.student_user_id",
                                  },
                                  {
                                  "name": "semester_id",
                                  "label": "Semester Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_semesterId",
                                  "alias" : "studentsemesters.semester_id",
                                  },
                                  {
                                  "name": "CGPA",
                                  "label": "CGPA",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_CGPA",
                                  "alias" : "studentsemesters.CGPA",
                                  },
                                  {
                                  "name": "SGPA",
                                  "label": "SGPA",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_SGPA",
                                  "alias" : "studentsemesters.SGPA",
                                  },
                                  {
                                  "name": "credits_acquired",
                                  "label": "Credits Acquired",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_creditsAcquired",
                                  "alias" : "studentsemesters.credits_acquired",
                                  },
                                  {
                                  "name": "attendance_delta",
                                  "label": "Attendance Delta",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "studentsemesters_attendanceDelta",
                                  "alias" : "studentsemesters.attendance_delta",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'studentsemesters_studentSemesterId' : 'student_semester_id',  'studentsemesters_studentUserId' : 'student_user_id',  'studentsemesters_semesterId' : 'semester_id',  'studentsemesters_CGPA' : 'CGPA',  'studentsemesters_SGPA' : 'SGPA',  'studentsemesters_creditsAcquired' : 'credits_acquired',  'studentsemesters_attendanceDelta' : 'attendance_delta',  'studentsemesters_status' : 'status',  'studentsemesters_createdBy' : 'created_by',  'studentsemesters_updatedBy' : 'updated_by',  'studentsemesters_createdAt' : 'created_at',  'studentsemesters_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;