const parameters = {
              "steps": [
                  {
                  "title": "Discounts Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "discounts",
                          "type": "section",
                          "title": "Discounts CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Discounts",
                          "childFields": [
                                {
                                  "name": "discounts_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "code",
                                  "label": "Code",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_code",
                                  "alias" : "discounts.code",
                                  },
                                  {
                                  "name": "description",
                                  "label": "Description",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_description",
                                  "alias" : "discounts.description",
                                  },
                                  {
                                  "name": "config_parameters",
                                  "label": "Config Parameters",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_configParameters",
                                  "alias" : "discounts.config_parameters",
                                  },
                                  {
                                  "name": "discount_percentage",
                                  "label": "Discount Percentage",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_discountPercentage",
                                  "alias" : "discounts.discount_percentage",
                                  },
                                  {
                                  "name": "usage_info",
                                  "label": "Usage Info",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_usageInfo",
                                  "alias" : "discounts.usage_info",
                                  },
                                  {
                                  "name": "is_active",
                                  "label": "Is Active",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_isActive",
                                  "alias" : "discounts.is_active",
                                  },
                                  {
                                  "name": "expires_at",
                                  "label": "Expires At",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "discounts_expiresAt",
                                  "alias" : "discounts.expires_at",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'discounts_id' : 'id',  'discounts_code' : 'code',  'discounts_description' : 'description',  'discounts_configParameters' : 'config_parameters',  'discounts_discountPercentage' : 'discount_percentage',  'discounts_usageInfo' : 'usage_info',  'discounts_isActive' : 'is_active',  'discounts_expiresAt' : 'expires_at',  'discounts_createdBy' : 'created_by',  'discounts_updatedBy' : 'updated_by',  'discounts_status' : 'status',  'discounts_createdAt' : 'created_at',  'discounts_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;