const parameters = {
              "steps": [
                  {
                  "title": "Incoming Audit Logs Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "incoming_audit_logs",
                          "type": "section",
                          "title": "Incoming Audit Logs CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Incoming_audit_logs",
                          "childFields": [
                                {
                                  "name": "incomingAuditLogs_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "request_type",
                                  "label": "Request Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_requestType",
                                  "alias" : "incoming_audit_logs.request_type",
                                  },
                                  {
                                  "name": "ai_credits_urdd_id",
                                  "label": "Ai Credits Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_aiCreditsUrddId",
                                  "alias" : "incoming_audit_logs.ai_credits_urdd_id",
                                  },
                                  {
                                  "name": "source",
                                  "label": "Source",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_source",
                                  "alias" : "incoming_audit_logs.source",
                                  },
                                  {
                                  "name": "request_data",
                                  "label": "Request Data",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_requestData",
                                  "alias" : "incoming_audit_logs.request_data",
                                  },
                                  {
                                  "name": "response_data",
                                  "label": "Response Data",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "incomingAuditLogs_responseData",
                                  "alias" : "incoming_audit_logs.response_data",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'incoming_audit_logs_id' : 'id',  'incoming_audit_logs_requestType' : 'request_type',  'incoming_audit_logs_aiCreditsUrddId' : 'ai_credits_urdd_id',  'incoming_audit_logs_source' : 'source',  'incoming_audit_logs_requestData' : 'request_data',  'incoming_audit_logs_responseData' : 'response_data',  'incoming_audit_logs_createdBy' : 'created_by',  'incoming_audit_logs_updatedBy' : 'updated_by',  'incoming_audit_logs_status' : 'status',  'incoming_audit_logs_createdAt' : 'created_at',  'incoming_audit_logs_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;