const parameters = {
              "steps": [
                  {
                  "title": "Outgoing Audit Logs Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "outgoing_audit_logs",
                          "type": "section",
                          "title": "Outgoing Audit Logs CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Outgoing_audit_logs",
                          "childFields": [
                                {
                                  "name": "outgoingAuditLogs_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "request_type",
                                  "label": "Request Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_requestType",
                                  "alias" : "outgoing_audit_logs.request_type",
                                  },
                                  {
                                  "name": "target_system",
                                  "label": "Target System",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_targetSystem",
                                  "alias" : "outgoing_audit_logs.target_system",
                                  },
                                  {
                                  "name": "ai_credits_urdd_id",
                                  "label": "Ai Credits Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_aiCreditsUrddId",
                                  "alias" : "outgoing_audit_logs.ai_credits_urdd_id",
                                  },
                                  {
                                  "name": "request_data",
                                  "label": "Request Data",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_requestData",
                                  "alias" : "outgoing_audit_logs.request_data",
                                  },
                                  {
                                  "name": "response_data",
                                  "label": "Response Data",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_responseData",
                                  "alias" : "outgoing_audit_logs.response_data",
                                  },
                                  {
                                  "name": "error_message",
                                  "label": "Error Message",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "outgoingAuditLogs_errorMessage",
                                  "alias" : "outgoing_audit_logs.error_message",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'outgoing_audit_logs_id' : 'id',  'outgoing_audit_logs_requestType' : 'request_type',  'outgoing_audit_logs_targetSystem' : 'target_system',  'outgoing_audit_logs_aiCreditsUrddId' : 'ai_credits_urdd_id',  'outgoing_audit_logs_requestData' : 'request_data',  'outgoing_audit_logs_responseData' : 'response_data',  'outgoing_audit_logs_errorMessage' : 'error_message',  'outgoing_audit_logs_createdBy' : 'created_by',  'outgoing_audit_logs_updatedBy' : 'updated_by',  'outgoing_audit_logs_status' : 'status',  'outgoing_audit_logs_createdAt' : 'created_at',  'outgoing_audit_logs_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;