const parameters = {
              "steps": [
                  {
                  "title": "User Devices Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "user_devices",
                          "type": "section",
                          "title": "User Devices CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "User_devices",
                          "childFields": [
                                {
                                  "name": "userDevices_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "user_id",
                                  "label": "User Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_userId",
                                  "alias" : "user_devices.user_id",
                                  },
                                  {
                                  "name": "device_token",
                                  "label": "Device Token",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_deviceToken",
                                  "alias" : "user_devices.device_token",
                                  },
                                  {
                                  "name": "device_name",
                                  "label": "Device Name",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_deviceName",
                                  "alias" : "user_devices.device_name",
                                  },
                                  {
                                  "name": "platform_version_id",
                                  "label": "Platform Version Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_platformVersionId",
                                  "alias" : "user_devices.platform_version_id",
                                  },
                                  {
                                  "name": "os_version",
                                  "label": "Os Version",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "userDevices_osVersion",
                                  "alias" : "user_devices.os_version",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'user_devices_userDeviceId' : 'user_device_id',  'user_devices_userId' : 'user_id',  'user_devices_deviceToken' : 'device_token',  'user_devices_deviceName' : 'device_name',  'user_devices_platformVersionId' : 'platform_version_id',  'user_devices_osVersion' : 'os_version',  'user_devices_createdBy' : 'created_by',  'user_devices_updatedBy' : 'updated_by',  'user_devices_status' : 'status',  'user_devices_createdAt' : 'created_at',  'user_devices_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;