const parameters = {
              "steps": [
                  {
                  "title": "Employees Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "employees",
                          "type": "section",
                          "title": "Employees CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Employees",
                          "childFields": [
                                {
                                  "name": "employees_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "department_id",
                                  "label": "Department Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_departmentId",
                                  "alias" : "employees.department_id",
                                  },
                                  {
                                  "name": "personal_domain_url",
                                  "label": "Personal Domain Url",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_personalDomainUrl",
                                  "alias" : "employees.personal_domain_url",
                                  },
                                  {
                                  "name": "urdd_id",
                                  "label": "Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_urddId",
                                  "alias" : "employees.urdd_id",
                                  },
                                  {
                                  "name": "qualification",
                                  "label": "Qualification",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_qualification",
                                  "alias" : "employees.qualification",
                                  },
                                  {
                                  "name": "salary",
                                  "label": "Salary",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_salary",
                                  "alias" : "employees.salary",
                                  },
                                  {
                                  "name": "start_date",
                                  "label": "Start Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_startDate",
                                  "alias" : "employees.start_date",
                                  },
                                  {
                                  "name": "end_date",
                                  "label": "End Date",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "employees_endDate",
                                  "alias" : "employees.end_date",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'employees_employeeId' : 'employee_id',  'employees_departmentId' : 'department_id',  'employees_personalDomainUrl' : 'personal_domain_url',  'employees_urddId' : 'urdd_id',  'employees_qualification' : 'qualification',  'employees_salary' : 'salary',  'employees_startDate' : 'start_date',  'employees_endDate' : 'end_date',  'employees_status' : 'status',  'employees_createdBy' : 'created_by',  'employees_updatedBy' : 'updated_by',  'employees_createdAt' : 'created_at',  'employees_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;