const parameters = {
              "steps": [
                  {
                  "title": "Supported Payment Methods Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "supported_payment_methods",
                          "type": "section",
                          "title": "Supported Payment Methods CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Supported_payment_methods",
                          "childFields": [
                                {
                                  "name": "supportedPaymentMethods_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "name",
                                  "label": "Name",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_name",
                                  "alias" : "supported_payment_methods.name",
                                  },
                                  {
                                  "name": "provider_details",
                                  "label": "Provider Details",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_providerDetails",
                                  "alias" : "supported_payment_methods.provider_details",
                                  },
                                  {
                                  "name": "discount_id",
                                  "label": "Discount Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_discountId",
                                  "alias" : "supported_payment_methods.discount_id",
                                  },
                                  {
                                  "name": "supported_currencies",
                                  "label": "Supported Currencies",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_supportedCurrencies",
                                  "alias" : "supported_payment_methods.supported_currencies",
                                  },
                                  {
                                  "name": "is_active",
                                  "label": "Is Active",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "supportedPaymentMethods_isActive",
                                  "alias" : "supported_payment_methods.is_active",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'supported_payment_methods_id' : 'id',  'supported_payment_methods_name' : 'name',  'supported_payment_methods_providerDetails' : 'provider_details',  'supported_payment_methods_discountId' : 'discount_id',  'supported_payment_methods_supportedCurrencies' : 'supported_currencies',  'supported_payment_methods_isActive' : 'is_active',  'supported_payment_methods_createdBy' : 'created_by',  'supported_payment_methods_updatedBy' : 'updated_by',  'supported_payment_methods_status' : 'status',  'supported_payment_methods_createdAt' : 'created_at',  'supported_payment_methods_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;