const parameters = {
              "steps": [
                  {
                  "title": "Transactions Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "transactions",
                          "type": "section",
                          "title": "Transactions CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Transactions",
                          "childFields": [
                                {
                                  "name": "transactions_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "urdd_id",
                                  "label": "Urdd Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_urddId",
                                  "alias" : "transactions.urdd_id",
                                  },
                                  {
                                  "name": "subscription_id",
                                  "label": "Subscription Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_subscriptionId",
                                  "alias" : "transactions.subscription_id",
                                  },
                                  {
                                  "name": "user_payment_method_id",
                                  "label": "User Payment Method Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_userPaymentMethodId",
                                  "alias" : "transactions.user_payment_method_id",
                                  },
                                  {
                                  "name": "amount",
                                  "label": "Amount",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_amount",
                                  "alias" : "transactions.amount",
                                  },
                                  {
                                  "name": "currency_id",
                                  "label": "Currency Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_currencyId",
                                  "alias" : "transactions.currency_id",
                                  },
                                  {
                                  "name": "transaction_type",
                                  "label": "Transaction Type",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_transactionType",
                                  "alias" : "transactions.transaction_type",
                                  },
                                  {
                                  "name": "gateway_response",
                                  "label": "Gateway Response",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_gatewayResponse",
                                  "alias" : "transactions.gateway_response",
                                  },
                                  {
                                  "name": "description",
                                  "label": "Description",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "transactions_description",
                                  "alias" : "transactions.description",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'transactions_id' : 'id',  'transactions_urddId' : 'urdd_id',  'transactions_subscriptionId' : 'subscription_id',  'transactions_userPaymentMethodId' : 'user_payment_method_id',  'transactions_amount' : 'amount',  'transactions_currencyId' : 'currency_id',  'transactions_transactionType' : 'transaction_type',  'transactions_gatewayResponse' : 'gateway_response',  'transactions_description' : 'description',  'transactions_createdBy' : 'created_by',  'transactions_updatedBy' : 'updated_by',  'transactions_status' : 'status',  'transactions_createdAt' : 'created_at',  'transactions_updatedAt' : 'updated_at'}"
              };
              module.exports = parameters;